### ISSUE TITLE
aog-visual-machine-linux-core-boot-error.md

### ISSUE THREAD

**Issue by JamborYao** [JamborYao/acn-content#19]
方案二:
如果方案一依然无法解决连接的问题, 建议您选择删除虚拟机保留磁盘, 然后基于该磁盘新建虚拟机. 修改内核参数:
注: 以下方案仅适用于 CentOS 和 RHEL,其他版本 Linux 略有不同, 仅供参考.如果业务生产对内核参数严格要求的, 请参考相关参数的说明, 酌情进行修改配置.
编辑 /etc/sysctl.conf 增加(修改以下参数): 
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10
保存并退出.
执行命令是上述改动立即生效:

这个结构不对，注意内容层次。

**Comment by v-tawe** [comment]
Actually Yes, Have Done.
