### ISSUE TITLE
Azure AD 与 Azure 订阅在 Azure 中国的架构限制与最佳实践

### ISSUE THREAD

**Issue by JamborYao** [JamborYao/acn-content#27]
若要了解有关如何在 Azure 中控制资源访问的详细信息，请参阅了解 Azure 中的资源访问权限；
1）标点符号
2）确保link格式正确以不影响publish后的访问，如有问题和johnny联系

**Comment by v-tawe** [comment]
1. Updated.
2. I confirmed the URL again and assured it is available.
