### ISSUE TITLE
如何激活 Trend Micro Deep Security Agent

### ISSUE THREAD

**Issue by JamborYao** [JamborYao/acn-content#33]
If you have strong with this title, keep it. If not, please keep the same with the dos. Please try to find it in Azure mooncake official site.

**Comment by v-tawe** [comment]
https://www.azure.cn/documentation/articles/virtual-machines-windows-classic-install-trend 
如何在 Windows VM 上安装和配置 Trend Micro Deep Security 即服务

This document in A.cn use "Trend Micro" instead of "趋势科技", so I changed it.
