### ISSUE TITLE
如何为Azure Service Bus和Azure IoT Hub生成SharedAccessSignature

### ISSUE THREAD

**Issue by JamborYao** [JamborYao/acn-content#5]
// HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(key)); for IoT Hub Service

      HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(key));   for service bus Service

代码部分你需要uncomment 一个hmac变量出来

**Comment by v-tawe** [comment]
Done
